package com.jwf.JavaWebFramework.misc.collections;

public enum PseudoClasses {
	ACTIVE, CHECKED, DISABLED, EMPTY, ENABLED, FIRST_CHILD, FIRST_OF_TYPE, FOCUS, HOVER, IN_RANGE, INVALID, LANG,
	LAST_CHILD, LAST_OF_TYPE, LINK, NTH_CHILD, NTH_LAST_CHILD, NTH_LAST_OF_TYPE, NTH_OF_TYPE, ONLY_OF_TYPE, ONLY_CHILD,
	OPTIONAL, OUT_OF_RANGE, READ_ONLY, READ_WRITE, REQUIRED, ROOT, TARGET, VALID, VISITED,
}
